### ISSUE TITLE
Fix table of contents

### ISSUE THREAD

**Issue by jasonlally** [DataSF/housing-data-hub#16]
There's a minor bug in the table of contents on the program and policies posts. For example, inclusionary housing. The scrollspy isn't quite working. I haven't looked into it yet, but I imagine it should be a quick fix. 

It's less of a functional problem, and more a user interface issue (active classes aren't being assigned correctly as the user scrolls). Also I may need to remove the summary link in the TOC and replace with a link to the top of the page (title).

**Comment by bexcitement** [comment]
@jasonlally -- is this issue closed?

**Comment by jasonlally** [comment]
No, this one is still an issue. The TOC is on each of the policy and program pages and is created automatically from the headers. It's a little wonky and I haven't had a chance to take a look at it, but please do if you have time :smile:

**Comment by jasonlally** [comment]
Closing this, thanks for helping with a fix
